# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['game_app.py']
APP_NAME = 'Sharing Stock'
DATA_FILES = ['game_data.csv']
OPTIONS = {
    'argv_emulation':True,
    'iconfile':'sharing_stock.icns',
    'plist': {
        'CFBundleName': '山软股市',
        'CFBundleDisplayName': '山软股市',
        'CFBundleGetInfoString': "SHARING IDEAS",
        'CFBundleIdentifier': "org.sharingideas.app",
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'CFHumanReadableCopyright': u"Copyright  © 2020, SHARING IDEAS, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
